apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  # "user" string encoded in base64
  user: dXNlcg==
  # "password" string encoded in base64
  password: cGFzc3dvcmQ=
